"""
Django settings for WLSLEVOVNIK project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(PROJECT_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    'home',
    'search',
    
    "ccm_app",
    "stream",
    "flex",
    "footers",
    "menus",
    "polozka",
    "socialni_site",
    "user_profile",

    "wagtail.contrib.settings", # přidáno kvůli sociální sítě

    # listingpage
    "wagtail.contrib.routable_page",

    # wagtailmenus
    "wagtailmenus",
    "wagtail.contrib.modeladmin",


    # longclaw
    # "wagtail_modeltranslation", "wagtail_modeltranslation.makemigrations", "wagtail_modeltranslation.migrate",
    # "wagtail.contrib.modeladmin",
    # "wagtail.contrib.settings",
    "wagtail.api.v2", 
    "djmoney",
    "rest_framework",
    "longclaw.core", "longclaw.configuration", "longclaw.shipping",
    "longclaw.products", "longclaw.orders", "longclaw.checkout",
    "longclaw.basket", "longclaw.stats", 
    # "catalog",



    'wagtail.contrib.forms',
    'wagtail.contrib.redirects',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',
    'wagtail.core',

    'modelcluster',
    'taggit',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',


    "django.contrib.sites", # přidáno kvůli django allauth

    # přidáno kvůli django allauth
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    # "allauth.socialaccount.providers.facebook",
    # "allauth.socialaccount.providers.google",
]


SITE_ID = 1 # přidáno kvůli django allauth


MIDDLEWARE = [
    'django.contrib.sessions.middleware.SessionMiddleware',

    "django.middleware.locale.LocaleMiddleware",  # should be after SessionMiddleware and before CommonMiddleware
    
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'wagtail.core.middleware.SiteMiddleware',
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
]



ROOT_URLCONF = 'WLSLEVOVNIK.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(PROJECT_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                "longclaw.configuration.context_processors.currency", # longclaw

                "wagtail.contrib.settings.context_processors.settings", # přidáno kvůli sociální sítě
                
                # přidáno kvůli wagtailmenus
                "django.template.context_processors.i18n",
                "django.template.context_processors.media",
                "django.template.context_processors.static",
                "django.template.context_processors.tz",
                "wagtailmenus.context_processors.wagtailmenus",
            ],
        },
    },
]



   # PŘIDÁNO KVŮLI DJANGO ALLAUTH
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]



WSGI_APPLICATION = 'WLSLEVOVNIK.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Europe/Prague"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

STATICFILES_DIRS = [
    os.path.join(PROJECT_DIR, 'static'),
]

# ManifestStaticFilesStorage is recommended in production, to prevent outdated
# Javascript / CSS assets being served from cache (e.g. after a Wagtail upgrade).
# See https://docs.djangoproject.com/en/2.2/ref/contrib/staticfiles/#manifeststaticfilesstorage
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


# Wagtail settings

WAGTAIL_SITE_NAME = "WLSLEVOVNIK"

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
BASE_URL = 'http://example.com'


# Longclaw settings

# The payment gateway to use. `BasePayment` is a dummy payment gateway for testing.
# Longclaw also offers 'BraintreePayment', 'PaypalVZeroPayment' and 'StripePayment'
PAYMENT_GATEWAY = 'longclaw.checkout.gateways.BasePayment'
# PRODUCT_VARIANT_MODEL = "catalog.ProductVariant"
PRODUCT_VARIANT_MODEL = "polozka.PolozkaVariantLONGCLAW"



    # PŘIDÁNO KVŮLI DJANGO ALLAUTH
LOGIN_URL                           = "/login"
LOGIN_REDIRECT_URL                  = "/"
ACCOUNT_AUTHENTICATION_METHOD       = "username_email"
ACCOUNT_CONFIRM_EMAIL_ON_GET        = True
ACCOUNT_EMAIL_REQUIRED              = True
ACCOUNT_EMAIL_VERIFICATION          = "mandatory"
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_LOGOUT_ON_GET               = True
ACCOUNT_LOGIN_ON_PASSWORD_RESET     = True
ACCOUNT_LOGOUT_REDIRECT_URL         = '/login/'
ACCOUNT_PRESERVE_USERNAME_CASING    = False
ACCOUNT_SESSION_REMEMBER            = True
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = False
ACCOUNT_USERNAME_BLACKLIST          = ["kalob", "admin", "god"] # nechci, aby se někdo přihlašoval pod těmito nicknames
ACCOUNT_USERNAME_MIN_LENGTH         = 2

