# Generated by Django 3.1.4 on 2021-01-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialni_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='instagram',
            field=models.URLField(blank=True, help_text='Instagram URL', null=True),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='linkedin',
            field=models.URLField(blank=True, help_text='Linkedin URL', null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='youtube',
            field=models.URLField(blank=True, help_text='Youtube URL', null=True),
        ),
    ]
