# Generated by Django 3.1.4 on 2021-01-17 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('socialni_site', '0002_auto_20210117_1924'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialMediaSettings',
            new_name='NastaveniSocialnichMedii',
        ),
    ]
