# Generated by Django 3.1.4 on 2021-01-27 20:46

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210114_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePagePolozky',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='polozky', to='home.homepage')),
            ],
            options={
                'verbose_name': 'Polozka name',
                'verbose_name_plural': 'Polozka name plural',
            },
        ),
    ]
