# Generated by Django 3.1.4 on 2021-01-27 20:58

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepagepolozky_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagepolozky',
            name='content',
        ),
        migrations.AddField(
            model_name='homepagepolozky',
            name='polozka',
            field=wagtail.core.fields.StreamField([('polozka_block', wagtail.core.blocks.StructBlock([('obrazek', wagtail.images.blocks.ImageChooserBlock(help_text='Obrázek položky', required=True)), ('nazev', wagtail.core.blocks.CharBlock(help_text='Název položky', required=True)), ('cena', wagtail.core.blocks.FloatBlock(help_text='Cena položky', required=True)), ('obchod', wagtail.core.blocks.CharBlock(help_text='Obchod položky', required=True)), ('pridat_do_kose', wagtail.core.blocks.URLBlock(help_text='Přidat do koše', required=True))]))], blank=True, null=True),
        ),
    ]
