# Generated by Django 3.1.4 on 2021-01-31 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210129_2027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePagePolozky',
        ),
    ]
