# Generated by Django 3.1.4 on 2021-02-02 20:37

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_ProfilePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('titlee', models.CharField(max_length=100, null=True)),
                ('description', wagtail.core.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'User profile_vn',
                'verbose_name_plural': 'User profile_vnp',
            },
            bases=('wagtailcore.page',),
        ),
    ]
