# Generated by Django 3.1.4 on 2021-01-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_menuitem_link_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='show_when',
            field=models.CharField(choices=[('always', 'Always'), ('logged_in', 'When logged in'), ('not_logged_in', 'When not logged in')], default='always', max_length=15),
        ),
    ]
